systemctl disable cups.path                                  
systemctl disable abrt-ccpp.service                          
systemctl disable abrt-oops.service                          
systemctl disable abrt-vmcore.service                        
systemctl disable abrt-xorg.service                          
systemctl disable abrtd.service                              
systemctl disable accounts-daemon.service                    
systemctl disable atd.service                                
systemctl disable bluetooth.service                          
systemctl disable chronyd.service                            
systemctl disable cups.service                               
systemctl disable dbus-org.bluez.service                     
systemctl disable dbus-org.freedesktop.ModemManager1.service 
systemctl disable display-manager.service                    
systemctl disable dmraid-activation.service                  
systemctl disable gdm.service                                
systemctl disable getty@.service                             
systemctl disable httpd.service                              
systemctl disable hypervkvpd.service                         
systemctl disable hypervvssd.service                         
systemctl disable ipmievd.service                            
systemctl disable iscsi.service                              
systemctl disable ksm.service                                
systemctl disable ksmtuned.service                           
systemctl disable libstoragemgmt.service                     
systemctl disable libvirtd.service                           
systemctl disable mariadb.service                            
systemctl disable mdmonitor.service                          
systemctl disable memcached.service                          
systemctl disable ModemManager.service                       
systemctl disable mongod.service                             
systemctl disable multipathd.service                         
systemctl disable netcf-transaction.service                  
systemctl disable neutron-dhcp-agent.service                 
systemctl disable neutron-l3-agent.service                   
systemctl disable neutron-linuxbridge-agent.service          
systemctl disable neutron-metadata-agent.service             
systemctl disable neutron-server.service                     
systemctl disable openstack-glance-api.service               
systemctl disable openstack-glance-registry.service          
systemctl disable openstack-nova-api.service                 
systemctl disable openstack-nova-cert.service                
systemctl disable openstack-nova-compute.service             
systemctl disable openstack-nova-conductor.service           
systemctl disable openstack-nova-consoleauth.service         
systemctl disable openstack-nova-novncproxy.service          
systemctl disable openstack-nova-scheduler.service           
systemctl disable qemu-guest-agent.service                   
systemctl disable rabbitmq-server.service                    
systemctl disable rngd.service                               
systemctl disable rtkit-daemon.service                       
systemctl disable smartd.service                             
systemctl disable spice-vdagentd.service                     
systemctl disable sysstat.service                            
systemctl disable vmtoolsd.service                           
systemctl disable cups.socket                                
systemctl disable iscsid.socket                              
systemctl disable iscsiuio.socket                            
systemctl disable rpcbind.socket                             
systemctl disable nfs-client.target                          
systemctl disable auditd.service                             

