systemctl enable cups.path                                  
systemctl enable abrt-ccpp.service                          
systemctl enable abrt-oops.service                          
systemctl enable abrt-vmcore.service                        
systemctl enable abrt-xorg.service                          
systemctl enable abrtd.service                              
systemctl enable accounts-daemon.service                    
systemctl enable atd.service                                
systemctl enable bluetooth.service                          
systemctl enable chronyd.service                            
systemctl enable cups.service                               
systemctl enable dbus-org.bluez.service                     
systemctl enable dbus-org.freedesktop.ModemManager1.service 
systemctl enable display-manager.service                    
systemctl enable dmraid-activation.service                  
systemctl enable gdm.service                                
systemctl enable getty@.service                             
systemctl enable httpd.service                              
systemctl enable hypervkvpd.service                         
systemctl enable hypervvssd.service                         
systemctl enable ipmievd.service                            
systemctl enable iscsi.service                              
systemctl enable ksm.service                                
systemctl enable ksmtuned.service                           
systemctl enable libstoragemgmt.service                     
systemctl enable libvirtd.service                           
systemctl enable mariadb.service                            
systemctl enable mdmonitor.service                          
systemctl enable memcached.service                          
systemctl enable ModemManager.service                       
systemctl enable mongod.service                             
systemctl enable multipathd.service                         
systemctl enable netcf-transaction.service                  
systemctl enable neutron-dhcp-agent.service                 
systemctl enable neutron-l3-agent.service                   
systemctl enable neutron-linuxbridge-agent.service          
systemctl enable neutron-metadata-agent.service             
systemctl enable neutron-server.service                     
systemctl enable openstack-glance-api.service               
systemctl enable openstack-glance-registry.service          
systemctl enable openstack-nova-api.service                 
systemctl enable openstack-nova-cert.service                
systemctl enable openstack-nova-compute.service             
systemctl enable openstack-nova-conductor.service           
systemctl enable openstack-nova-consoleauth.service         
systemctl enable openstack-nova-novncproxy.service          
systemctl enable openstack-nova-scheduler.service           
systemctl enable qemu-guest-agent.service                   
systemctl enable rabbitmq-server.service                    
systemctl enable rngd.service                               
systemctl enable rtkit-daemon.service                       
systemctl enable smartd.service                             
systemctl enable spice-vdagentd.service                     
systemctl enable sysstat.service                            
systemctl enable vmtoolsd.service                           
systemctl enable cups.socket                                
systemctl enable iscsid.socket                              
systemctl enable iscsiuio.socket                            
systemctl enable rpcbind.socket                             
systemctl enable nfs-client.target                          
systemctl enable auditd.service                             

